name: SSH Command Execution

on:
  schedule:
    - cron: '0 * * * *'  # 每小时的第0分钟执行

jobs:
  ssh-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH and run command
        run: |
          echo "Starting SSH command execution"
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd /domains && screen -S alist-server -d -m ./alist server"
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

- name: Install sshpass
  run: |
    sudo apt-get update
    sudo apt-get install -y sshpass
